name: flutter_easyloading_plus
description: A clean and lightweight loading/toast widget for Flutter, easy to use without context. Support iOS, Android, and Web with enhanced customization.
version: 3.2.0
repository: https://github.com/rizkyghofur/flutter_easyloading_plus
issue_tracker: https://github.com/rizkyghofur/flutter_easyloading_plus/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
